# Generated by Django 4.0.1 on 2022-02-16 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craetedDate', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('deletedDate', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('servicename', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
                ('logtype', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craetedDate', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('deletedDate', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('pagename', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craetedDate', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('deletedDate', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('typeName', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craetedDate', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('deletedDate', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('rolename', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='T_aimag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aimagCode', models.CharField(max_length=2)),
                ('aimagName', models.CharField(max_length=100)),
                ('aimagDaraalal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='T_chiglel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiglelName', models.CharField(max_length=250)),
                ('chiglelDaraalal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='T_sum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumCode', models.CharField(max_length=4)),
                ('sumName', models.CharField(max_length=100)),
                ('sumDaraalal', models.IntegerField(default=0)),
                ('aimag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etax.t_aimag')),
            ],
        ),
        migrations.CreateModel(
            name='Role2Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etax.pages')),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etax.perm')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etax.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craetedDate', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('deletedDate', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('payername', models.CharField(max_length=200)),
                ('regnum', models.CharField(max_length=30)),
                ('sitdate', models.DateTimeField(blank=True, null=True, verbose_name='sitdate created')),
                ('payerNum', models.CharField(max_length=11)),
                ('lastname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('regdate', models.DateTimeField(blank=True, null=True, verbose_name='regdate created')),
                ('aimagNum', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etax.t_aimag')),
                ('chiglelNum', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etax.t_chiglel')),
                ('payerType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etax.payertype')),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etax.roles')),
                ('sumNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etax.t_sum')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pages',
            name='role2Page',
            field=models.ManyToManyField(through='etax.Role2Page', to='etax.Roles'),
        ),
    ]
