# Generated by Django 4.0.1 on 2022-02-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('mn', 'mon'), ('eng', 'engo')], default='python', max_length=100)),
                ('style', models.CharField(choices=[('mn', 'mon'), ('eng', 'engo')], default='friendly', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
